mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com:
      jw: debug
    org:
      springframework: error
  path: /tmp/log
  root: error